# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('account_email', models.CharField(max_length=50, unique=True)),
                ('account_status', models.CharField(max_length=50)),
                ('login_password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('account_id', models.CharField(max_length=50)),
                ('dweets_id', models.CharField(max_length=50)),
                ('comment_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('comment_data', models.TextField()),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='Dweet',
            fields=[
                ('account_id', models.CharField(max_length=50)),
                ('dweet_data', models.TextField()),
                ('dweet_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'dweet',
            },
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('followed_user_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'follower',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField()),
                ('account_id', models.CharField(max_length=50)),
                ('last_used_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'session',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_profile_name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('account_id', 'entity_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set([('user_id', 'followed_user_id')]),
        ),
    ]
