# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20171105_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 22, 5, 55, 286138, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 5, 22, 6, 4, 630734, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
